version: '3.2'

services:
  mongo_db:
    image: mongo:5.0.2
    container_name: mongodb_shootergame
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./data/db:/data/db
    networks:
      - shooter-game-net
  

  app_backend:
    container_name: shooter-game-backend
    depends_on:
      - mongo_db
    build: ./spring-boot-backend
    ports:
      - 8080:8080
    networks:
      - shooter-game-net

  app_frontend:
    container_name: shooter-game-frontend
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - shooter-game-net

networks:
  shooter-game-net:
    name: shooter-game-net
    driver: bridge
