version: '3.2'

services:
  mongo_db:
    image: mongo:5.0.2
    container_name: mongo_db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./data/db:/data/db
  
  app:
    container_name: shooter-game-app
    depends_on:
      - mongo_db
    build: ./spring-boot-backend
    ports:
      - 8080:8080
    develop:
      watch:
        - action: rebuild
          path: .
          # ignore:
          #   - node_modules/



